### ISSUE TITLE
remote slurm connection

### ISSUE THREAD

**Issue by xuhan-96** [deepmodeling/dflow#171]
Hello, I am trying to connect slurm on my local machine and submit jobs remotely.

My remote slurm function is:
`   slurm_remote_executor = SlurmRemoteExecutor(
    host="**.**.**.**",
    port=22,
    username="**",
    private_key_file="$HOME/.ssh/id_rsa", 
    workdir="***",
    header="***", 
    )
`

When I execute this function, the logging information is: **Permission denied (gssapi-with-mic, password)**

So how to solve this problem? Do I need to make other configurations on my local machine?  So far I only generated RSA key and put the public key on slurm system ($HOME/.ssh/authorized_keys).

By the way, normally when I ssh the slurm, I need **double authoriation, both password/public key and OTP**.

**Comment by zjgemi** [comment]
Double authorization usually means manual intervention by design, which is not likely to be done automatically. Maybe you can try if DPDispatcher supports for this. But I don't think so.

**Comment by xuhan-96** [comment]
> Double authorization usually means manual intervention by design, which is not likely to be done automatically. Maybe you can try if DPDispatcher supports for this. But I don't think so.

Thanks for your reply, I will check that!
