### ISSUE TITLE
can not download artifact on argo UI

### ISSUE THREAD

**Issue by kianpu34593** [deepmodeling/dflow#30]
Hi,

I finished running a workflow using slices. But I can't download artifacts online. It shows the following message:
`failed to get directory: stat /tmp/artifact3877355615/.dflow/34915d90-9d15-4956-a41e-596473177a64: not a directory`

At the same time, I can download the artifact using `dflow.download_artifact`. 

One more thing. I can download the outputs on the UI using the same argo but running a different code without Slices.

What's the problem?

The argo UI for the one that didn't work:
<img width="1348" alt="Screen Shot 2022-07-20 at 9 48 17 AM" src="https://user-images.githubusercontent.com/59935793/179878543-ec343cc0-7841-4b46-9e2d-1dc8097596f2.png">

**Comment by zjgemi** [comment]
I have noticed this problem. As dflow project has not began to develop UI part, maybe you can open an issue for Argo Workflows. For workarounds, you can either download the artifact using dflow.download_artifact, or from Minio UI (http://localhost:9001 for localhost)

**Comment by kianpu34593** [comment]
Awesome, thank you very much!
