### ISSUE TITLE
running dflow on jupyter notebook -unexpected bug: No module named 'cloudpickle'

### ISSUE THREAD

**Issue by veritas496** [deepmodeling/dflow#31]
<img width="1466" alt="截屏2022-07-20 14 35 21" src="https://user-images.githubusercontent.com/56317222/179913658-a143ae3c-36f6-44fc-94cb-12f6c2259072.png">
when i run the code of defining steps, there was an unexpected bug, as shown in figure. 
`
wf = Workflow("slices")
hello = Step("hello",
            PythonOPTemplate(Hello, image="python:3.8",
                            slices=Slices("{{item}}",
                                        input_parameter=["filename"],
                                        output_artifact=["out_art"]
                                        )
                            ),
            parameters={"filename": [f"f{x}.txt" for x in range(10)]},
            key="no1",
            with_param=argo_range(10))
check = Step("check",
            PythonOPTemplate(Check, image="python:3.8"),
            artifacts={"filename": hello.outputs.artifacts["out_art"]},
            )
wf.add(hello)
wf.add(check)
wf.submit();
`

could you please tell me how I can solve it? thanks for your time in advance.

**Comment by kianpu34593** [comment]
the problem is that cloudpickle needs to be installed. 
`pip install cloudpickle`

But I suggest this package includes in the dependency of pydflow.

**Comment by zjgemi** [comment]
We didn't include cloudpickle for pydflow on purpose, because we didn't want to add a dependency due to a rarely used branch. Perhaps we can propose a vote on this.

**Comment by zjgemi** [comment]
Please comment "+1" below if you approve of including cloudpickle as a default dependency of pydflow, otherwise please comment "-1" below.

**Comment by kianpu34593** [comment]
+1
