### ISSUE TITLE
opcode error in cloudpickle

### ISSUE THREAD

**Issue by zezhong-zhang** [deepmodeling/dflow#445]
## Summary
running `test_slices.py` is working fine, but the `dflow-slices.ipynb` gives opcode error.

maybe related to the object in different version mentioned in [here](https://stackoverflow.com/questions/72935514/cant-solve-systemerror-unknown-opcode) and https://github.com/cloudpipe/cloudpickle/issues/293? 

## Diagnostics
The log of failed task in `dflow-slices.ipynb` is as attached. 
> Traceback (most recent call last):
>   File "/argo/staging/script", line 14, in <module>
>     Hello = cloudpickle.loads(b'\x80\x05\x95\xb2$\x00\x00\x00\x00\x00\x00\x8c\x17cloudpickle.cloudpickle\x94\x8c\x14_make_skeleton_class\x94\x93\x94(\x8c\x03abc\x94\x8c\x07ABCMeta\x94\x93\x94\x8c\x05Hello\x94\x8c\x0fdflow.python.op\x94\x8c\x02OP\x94\x93\x94\x85\x94}\x94\x8c ea6a72178c7145bb89318e87d30e090e\x94Nt\x94R\x94\x8c\x1ccloudpickle.cloudpickle_fast\x94\x8c\x0f_class_setstate\x94\x93\x94h\x0e}\x94(\x8c\n__module__\x94\x8c\x08__main__\x94\x8c\x08__init__\x94h\x00\x8c\x0e_make_function\x94\x93\x94(h\x00\x8c\r_builtin_type\x94\x93\x94\x8c\x08CodeType\x94\x85\x94R\x94(K\x01K\x00K\x00K\x01K\x01K\x03C\x06\x97\x00d\x00S\x00\x94N\x85\x94)\x8c\x04self\x94\x85\x94\x8c$/tmp/ipykernel_2148263/3075924370.py\x94h\x15\x8c\x0eHello.__init__\x94K\x02C\x07\x80\x00\xd8\x08\x0c\x88\x04\x94C\x00\x94))t\x94R\x94}\x94(\x8c\x0b__package__\x94N\x8c\x08__name__\x94h\x14uNNNt\x94R\x94h\x0f\x8c\x12_function_setstate\x94\x93\x94h+}\x94}\x94(h)h\x15\x8c\x0c__qualname__\x94h"\x8c\x0f__annotations__\x94}\x94\x8c\x0e__kwdefaults__\x94N\x8c\x0c__defaults__\x94Nh\x13h\x14\x8c\x07__doc__\x94N\x8c\x0b__closure__\x94N\x8c\x17_cloudpickle_submodules\x94]\x94\x8c\x0b__globals__\x94}\x94u\x86\x94\x86R0\x8c\x0eget_input_sign\x94\x8c\x08builtins\x94\x8c\x0bclassmethod\x94\x93\x94h\x17(h\x1c(K\x01K\x00K\x00K\x01K\x04K\x03C.\x97\x00t\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00d\x01t\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00i\x01\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00S\x00\x94N\x8c\x08filename\x94\x86\x94\x8c\x08OPIOSign\x94\x8c\x03str\x94\x86\x94\x8c\x03cls\x94\x85\x94h!h<\x8c\x14Hello.get_input_sign\x94K\x05C\x1e\x80\x00\xe5\x0f\x17\xd8\x0c\x16\x9d\x03\xf0\x03\x02\x19\n\xf1\x00\x02\x10\x0b\xf4\x00\x02\x10\x0b\xf0\x00\x02\t\x0b\x94h$))t\x94R\x94h\'NNNt\x94R\x94h-hM}\x94}\x94(h)h<h0hHh1}\x94h3Nh4Nh\x13h\x14h5Nh6Nh7]\x94h9}\x94hC\x8c\x11dflow.python.opio\x94hC\x93\x94su\x86\x94\x86R0\x85\x94R\x94\x8c\x0fget_output_sign\x94h?h\x17(h\x1c(K\x01K\x00K\x00K\x01K\x06K\x03CH\x97\x00t\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00d\x01t\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00t\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00i\x01\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00S\x00\x94N\x8c\x07out_art\x94\x86\x94hC\x8c\x08Artifact\x94hD\x87\x94hF\x85\x94h!hX\x8c\x15Hello.get_output_sign\x94K\x0bC$\x80\x00\xe5\x0f\x17\xd8\x0c\x15\x95x\xa5\x03\x91}\x94}\xf0\x03\x02\x19\n\xf1\x00\x02\x10\x0b\xf4\x00\x02\x10\x0b\xf0\x00\x02\t\x0b\x94h$))t\x94R\x94h\'NNNt\x94R\x94h-hd}\x94}\x94(h)hXh0h_h1}\x94h3Nh4Nh\x13h\x14h5Nh6Nh7]\x94h9}\x94(hChTh\\hSh\\\x93\x94uu\x86\x94\x86R0\x85\x94R\x94\x8c\x07execute\x94h\x17(h\x1c(K\x02K\x00K\x00K\x03K\x05K\x13C\xd8\x95\x01\x97\x00t\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa0\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00|\x01|\x00\xa0\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa6\x00\x00\x00\xab\x00\x00\x00\x00\x00\x00\x00\x00\x00d\x01\xa6\x03\x00\x00\xab\x03\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x02\x00\x89\x03|\x00|\x01\xa6\x02\x00\x00\xab\x02\x00\x00\x00\x00\x00\x00\x00\x00}\x02t\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa0\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00|\x02|\x00\xa0\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa6\x00\x00\x00\xab\x00\x00\x00\x00\x00\x00\x00\x00\x00d\x02\xa6\x03\x00\x00\xab\x03\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00|\x02S\x00\x94N\x88\x89\x87\x94(h\x08\x8c\x10_check_signature\x94h<hXt\x94h\x1f\x8c\x05op_in\x94\x8c\x06op_out\x94\x87\x94\x8cR/home/zzhang/miniconda3/envs/dflow/lib/python3.11/site-packages/dflow/python/op.py\x94\x8c\x0cwrapper_exec\x94\x8c(OP.exec_sign_check.<locals>.wrapper_exec\x94KsCa\xf8\x80\x00\xe5\x0c\x0e\xd7\x0c\x1f\xd2\x0c\x1f\xa0\x05\xa0t\xd7\':\xd2\':\xd1\'<\xd4\'<\xb8d\xd1\x0cC\xd4\x0cC\xd0\x0cC\xd8\x15\x19\x90T\x98$\xa0\x05\xd1\x15&\xd4\x15&\x88F\xdd\x0c\x0e\xd7\x0c\x1f\xd2\x0c\x1f\xa0\x06\xa8\x04\xd7(<\xd2(<\xd1(>\xd4(>\xc0\x05\xd1\x0cF\xd4\x0cF\xd0\x0cF\xd8\x13\x19\x88M\x94h$\x8c\x04func\x94\x85\x94)t\x94R\x94}\x94(h(\x8c\x0cdflow.python\x94h)h\x07\x8c\x08__file__\x94\x8cR/home/zzhang/miniconda3/envs/dflow/lib/python3.11/site-packages/dflow/python/op.py\x94uNNh\x00\x8c\x10_make_empty_cell\x94\x93\x94)R\x94\x85\x94t\x94R\x94h-h\x87}\x94\x8c\x0b__wrapped__\x94h\x17(h\x1c(K\x02K\x00K\x00K\x04K\x05K\x03C\xf8\x97\x00t\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00|\x01d\x01\x19\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa0\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00d\x02\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00d\x03\x19\x00\x00\x00\x00\x00\x00\x00\x00\x00d\x04d\x00\x85\x02\x19\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00}\x02t\x05\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00|\x01d\x01\x19\x00\x00\x00\x00\x00\x00\x00\x00\x00d\x05\xa6\x02\x00\x00\xab\x02\x00\x00\x00\x00\x00\x00\x00\x00\xa0\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00d\x06|\x02z\x05\x00\x00\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00t\t\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00d\x07|\x01d\x01\x19\x00\x00\x00\x00\x00\x00\x00\x00\x00i\x01\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00}\x03|\x03S\x00\x94(NhA\x8c\x01.\x94K\x00K\x01\x8c\x01w\x94h\x06hZt\x94(\x8c\x03int\x94\x8c\x05split\x94\x8c\x04open\x94\x8c\x05write\x94\x8c\x04OPIO\x94t\x94(h\x1fhs\x8c\x08file_num\x94htt\x94h!hn\x8c\rHello.execute\x94K\x11C\x7f\x80\x00\xf5\n\x00\x14\x17\x90u\x98Z\xd4\x17(\xd7\x17.\xd2\x17.\xa8s\xd1\x173\xd4\x173\xb0A\xd4\x176\xb0q\xb0r\xb0r\xd4\x17:\xd1\x13;\xd4\x13;\x88\x08\xdd\x08\x0c\x88U\x90:\xd4\r\x1e\xa0\x03\xd1\x08$\xd4\x08$\xd7\x08*\xd2\x08*\xa87\xb0X\xd1+=\xd1\x08>\xd4\x08>\xd0\x08>\xdd\x11\x15\xd8\x0c\x15\x90u\x98Z\xd4\x17(\xf0\x03\x02\x17\n\xf1\x00\x02\x12\x0b\xf4\x00\x02\x12\x0b\x88\x06\xf0\x06\x00\x10\x16\x88\r\x94h$))t\x94R\x94h\'NNNt\x94R\x94h-h\x9b}\x94}\x94(h)hnh0h\x96h1}\x94(hshSh\x92\x93\x94\x8c\x06return\x94h\x9fuh3Nh4Nh\x13h\x14h5Nh6Nh7]\x94h9}\x94(h\x90h\x17(h\x1c(K\x01K\x00K\x00K\x03K\x05K\x0fCP\x97\x00|\x00d\x01v\x00r\x13t\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00d\x02|\x00\x9b\x00d\x03\x9d\x03\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00\x82\x01t\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00|\x00g\x01|\x01\xa2\x01R\x00i\x00|\x02\xa4\x01\x8e\x01S\x00\x94(N(K\x00K\x01K\x02\x91\x94\x8c\x1eIPython won\'t let you open fd=\x94\x8ci by default as it is likely to crash IPython. If you know what you are doing, you can use builtins\' open.\x94t\x94\x8c\nValueError\x94\x8c\x07io_open\x94\x86\x94\x8c\x04file\x94\x8c\x04args\x94\x8c\x06kwargs\x94\x87\x94\x8c`/home/zzhang/miniconda3/envs/dflow/lib/python3.11/site-packages/IPython/core/interactiveshell.py\x94\x8c\x0e_modified_open\x94h\xb0M\x13\x01CU\x80\x00\xe0\x07\x0b\x88y\xd0\x07\x18\xd0\x07\x18\xdd\x0e\x18\xf0\x02\x02\r*\xa8T\xf0\x00\x02\r*\xf0\x00\x02\r*\xf0\x00\x02\r*\xf1\x03\x04\x0f\n\xf4\x00\x04\x0f\n\xf0\x00\x04\t\n\xf5\x0c\x00\x0c\x13\x904\xd0\x0b)\x98$\xd0\x0b)\xd0\x0b)\xd0\x0b)\xa0&\xd0\x0b)\xd0\x0b)\xd0\x04)\x94h$))t\x94R\x94}\x94(h(\x8c\x0cIPython.core\x94h)\x8c\x1dIPython.core.interactiveshell\x94h\x80h\xafuNNNt\x94R\x94h-h\xb8}\x94h\x89\x8c\x02io\x94\x8c\x04open\x94\x93\x94s}\x94(h)\x8c\x04open\x94h0\x8c\x04open\x94h1}\x94h3Nh4Nh\x13h\xbah5Xv\x17\x00\x00Open file and return a stream.  Raise OSError upon failure.\n\nfile is either a text or byte string giving the name (and the path\nif the file isn\'t in the current working directory) of the file to\nbe opened or an integer file descriptor of the file to be\nwrapped. (If a file descriptor is given, it is closed when the\nreturned I/O object is closed, unless closefd is set to False.)\n\nmode is an optional string that specifies the mode in which the file\nis opened. It defaults to \'r\' which means open for reading in text\nmode.  Other common values are \'w\' for writing (truncating the file if\nit already exists), \'x\' for creating and writing to a new file, and\n\'a\' for appending (which on some Unix systems, means that all writes\nappend to the end of the file regardless of the current seek position).\nIn text mode, if encoding is not specified the encoding used is platform\ndependent: locale.getencoding() is called to get the current locale encoding.\n(For reading and writing raw bytes use binary mode and leave encoding\nunspecified.) The available modes are:\n\n========= ===============================================================\nCharacter Meaning\n--------- ---------------------------------------------------------------\n\'r\'       open for reading (default)\n\'w\'       open for writing, truncating the file first\n\'x\'       create a new file and open it for writing\n\'a\'       open for writing, appending to the end of the file if it exists\n\'b\'       binary mode\n\'t\'       text mode (default)\n\'+\'       open a disk file for updating (reading and writing)\n========= ===============================================================\n\nThe default mode is \'rt\' (open for reading text). For binary random\naccess, the mode \'w+b\' opens and truncates the file to 0 bytes, while\n\'r+b\' opens the file without truncation. The \'x\' mode implies \'w\' and\nraises an `FileExistsError` if the file already exists.\n\nPython distinguishes between files opened in binary and text modes,\neven when the underlying operating system doesn\'t. Files opened in\nbinary mode (appending \'b\' to the mode argument) return contents as\nbytes objects without any decoding. In text mode (the default, or when\n\'t\' is appended to the mode argument), the contents of the file are\nreturned as strings, the bytes having been first decoded using a\nplatform-dependent encoding or using the specified encoding if given.\n\nbuffering is an optional integer used to set the buffering policy.\nPass 0 to switch buffering off (only allowed in binary mode), 1 to select\nline buffering (only usable in text mode), and an integer > 1 to indicate\nthe size of a fixed-size chunk buffer.  When no buffering argument is\ngiven, the default buffering policy works as follows:\n\n* Binary files are buffered in fixed-size chunks; the size of the buffer\n  is chosen using a heuristic trying to determine the underlying device\'s\n  "block size" and falling back on `io.DEFAULT_BUFFER_SIZE`.\n  On many systems, the buffer will typically be 4096 or 8192 bytes long.\n\n* "Interactive" text files (files for which isatty() returns True)\n  use line buffering.  Other text files use the policy described above\n  for binary files.\n\nencoding is the name of the encoding used to decode or encode the\nfile. This should only be used in text mode. The default encoding is\nplatform dependent, but any encoding supported by Python can be\npassed.  See the codecs module for the list of supported encodings.\n\nerrors is an optional string that specifies how encoding errors are to\nbe handled---this argument should not be used in binary mode. Pass\n\'strict\' to raise a ValueError exception if there is an encoding error\n(the default of None has the same effect), or pass \'ignore\' to ignore\nerrors. (Note that ignoring encoding errors can lead to data loss.)\nSee the documentation for codecs.register or run \'help(codecs.Codec)\'\nfor a list of the permitted encoding error strings.\n\nnewline controls how universal newlines works (it only applies to text\nmode). It can be None, \'\', \'\\n\', \'\\r\', and \'\\r\\n\'.  It works as\nfollows:\n\n* On input, if newline is None, universal newlines mode is\n  enabled. Lines in the input can end in \'\\n\', \'\\r\', or \'\\r\\n\', and\n  these are translated into \'\\n\' before being returned to the\n  caller. If it is \'\', universal newline mode is enabled, but line\n  endings are returned to the caller untranslated. If it has any of\n  the other legal values, input lines are only terminated by the given\n  string, and the line ending is returned to the caller untranslated.\n\n* On output, if newline is None, any \'\\n\' characters written are\n  translated to the system default line separator, os.linesep. If\n  newline is \'\' or \'\\n\', no translation takes place. If newline is any\n  of the other legal values, any \'\\n\' characters written are translated\n  to the given string.\n\nIf closefd is False, the underlying file descriptor will be kept open\nwhen the file is closed. This does not work when a file name is given\nand must be True in that case.\n\nA custom opener can be used by passing a callable as *opener*. The\nunderlying file descriptor for the file object is then obtained by\ncalling *opener* with (*file*, *flags*). *opener* must return an open\nfile descriptor (passing os.open as *opener* results in functionality\nsimilar to passing None).\n\nopen() returns a file object whose type depends on the mode, and\nthrough which the standard file operations such as reading and writing\nare performed. When open() is used to open a file in a text mode (\'w\',\n\'r\', \'wt\', \'rt\', etc.), it returns a TextIOWrapper. When used to open\na file in a binary mode, the returned class varies: in read binary\nmode, it returns a BufferedReader; in write binary and append binary\nmodes, it returns a BufferedWriter, and in read/write mode, it returns\na BufferedRandom.\n\nIt is also possible to use a string or bytearray as a file for both\nreading and writing. For strings StringIO can be used like a file\nopened in a text mode, and for bytes a BytesIO can be used like a file\nopened in a binary mode.\x94h6Nh7]\x94h9}\x94h\xa9h\xbcsu\x86\x94\x86R0h\x92h\x9fuu\x86\x94\x86R0s}\x94(h)hnh0h\x96h1h\x9eh3Nh4Nh\x13h\x14h5Nh6h\x00\x8c\n_make_cell\x94\x93\x94h\x9b\x85\x94R\x94\x85\x94h7]\x94h9}\x94h\x08h\tsu\x86\x94\x86R0h5N\x8c\x13__abstractmethods__\x94(\x91\x94\x8c\t_abc_impl\x94]\x94u}\x94\x86\x94\x86R0.')
> TypeError: code() takes at most 16 arguments (18 given)

**Comment by zjgemi** [comment]
Thanks for reporting the problem. So which version of Python is installed in your local environment?

**Comment by zezhong-zhang** [comment]
I used miniconda to create an new environment, then do `pip install pydflow`, which install python 3.11.3 automatically.

**Comment by zjgemi** [comment]
I reproduced this issue between python 3.11 and python 3.8. In the PR above, I specify the version of python image to be the same with the local one. Fortunately, cloudpickle is only used in the interactive mode. This problem is not supposed to affect the cases without the use of notebook.

**Comment by zezhong-zhang** [comment]
That's quick!
