### ISSUE TITLE
allow arbitrary header for submission script in DispatcherExecutor

### ISSUE THREAD

**Issue by zezhong-zhang** [deepmodeling/dflow#457]
# Summary

I know this is strange, but our cluster put a PBS layer on top of the Slurm system. However that PBS layer is not exactly the same as the genuine PBS, this brings several issues:
- The header and qstat has some keys missing or different, I cannot simply uses PBS as `batch_type`. 
- The submission of CPU/GPU job also has to load the corresponding module, instead of specify the queue partition in normal cluster. This means before the job submission the shell has to run like `module swap cluster/dodrio/gpu_rome_a100`.  

To address the problem, I am wondering: 
- Is it possible to allow arbitrary header in DispatcherExecutor as in SlurmRemoteExecuton? 
- Where to find the job submission and get status in the code so that I can change them accordingly. 

I modified those in `pbs.py` in dpdispatcher to run the remote submission and retrieve correctly, but not so sure about where to find them in DispatcherExecutor.

**Comment by zjgemi** [comment]
Refer to [DPDispatcher's documents](https://docs.deepmodeling.com/projects/dpdispatcher/en/latest/index.html).
- `custom_flags` in resources passes extra lines to job submitting script header. Specify by `DispatcherExecutor(resources_dict={"custom_flags": "xxx"})`.
- `module_list` assigns modules to be loaded on HPC system before submitting jobs. Specify by `DispatcherExecutor(resources_dict={"module_list": ["xxx"]})`.
- For the modification of dpdispatcher, the standard operation procedure to make it work will be
1. Build a new docker image with the modified code using the [Dockerfile](https://github.com/deepmodeling/dpdispatcher/blob/master/Dockerfile) in dpdispatcher's repo.
2. Push the docker image to a registry. E.g. a repository on Docker Hub yourname/dpdispatcher:patched.
3. Specify dispatcher image by `DispatcherExecutor(image="yourname/dpdispatcher:patched")`

**Comment by zjgemi** [comment]
I will close this issue. Feel free to reopen it if you still have problems.

**Comment by zjgemi** [comment]
No need to hostname, password, key_filename, port, etc in the machine dict. Specially, path of the private key file in the container is generally different from that local. key_filename is specified by dflow automatically. Specify key_filename in the machine dict will cause wrong path for the key file.

**Comment by zezhong-zhang** [comment]
Thanks, the authentication issue is resolved. 
But it gives another issue when using the same dpdispatcher locally. There is only `select_node_line` in the  `pbs_script_header_dict`, not `select` but strangely the error suggest that it is somehow passed to the dict.
![image](https://github.com/deepmodeling/dflow/assets/13212584/342fb5e9-c0b9-4024-9662-a44b4587447e)

**Comment by zezhong-zhang** [comment]
Solved, the patched dispatcher image should specify in the `DispatcherExecutor`, not the `PythonOPTemplate`. We can close this now.
