### ISSUE TITLE
how to access the intermediate files generated during each step?

### ISSUE THREAD

**Issue by Satinelamp** [deepmodeling/dflow#64]
If I run VASP in one step with a container, is it possible to access the intermediated files generated by VASP except for the output artifact?
Usually, I run VASP on the HPC, and the CONTCAR, DOSCAR, PROCAR files, etc. generated from VASP are stored on the hard drive of the HPC, I could download them and do postprocessing whenever I need.
If I use dflow, all the generated files are stored in the containers, except the output artifacts, all the intermediated files seem to go to ashes after the workflow finishes, as the containers go to ashes.

**Comment by zjgemi** [comment]
If the container's running, login the container to access the files directly.
If the container has been completed, nope. If the intermediated files may be useful, you must explicitly specify the whole working directory as the output artifact. That's necessary in the logic of container.
