### ISSUE TITLE
bug: success ratio count wrong when using `continue_on_success_ratio`

### ISSUE THREAD

**Issue by saltball** [deepmodeling/dflow#76]
## Checklist

 

* [x] Checked the syntax is legal within dflow.
* [x] Tested using the latest version.

## Summary

What happened/what you expected to happen?

> When I run the script [test_success_ratio.py](https://github.com/deepmodeling/dflow/blob/master/examples/test_success_ratio.py), the check-step `check-success-ratio` always give `Succeeded` even the 5 steps success less than the threshold.
![image](https://user-images.githubusercontent.com/20452348/183874638-bf4ae32f-4e49-4184-8e6f-281acc95abe7.png)
It seems that check-step received wrong inputs:
![image](https://user-images.githubusercontent.com/20452348/183874763-8a99ba03-7ff8-4a7f-bf17-8ddb7e1dfe24.png)

What version are you running?
> <v1.3.1

## Diagnostics

see [test_success_ratio.py](https://github.com/deepmodeling/dflow/blob/master/examples/test_success_ratio.py).

I suspect that argoflow is unable to pass the `dflow_success_tag` from the execution of the wrong step into the `check-step` inputs, but I haven't thought of a good solution.

**Comment by zjgemi** [comment]
That is a regression of Argo. I tested version 3.2.6, everything's ok.
<img width="1366" alt="截屏2022-08-12 下午9 06 57" src="https://user-images.githubusercontent.com/27884723/184360271-d7335738-0c91-4c45-a2e0-867091997b3a.png">
While since version 3.2.7, the problem exists. Is there any workaround?

**Comment by saltball** [comment]
Does Argoflow no longer support output from unsuccessful nodes after v3.2.7? @zjgemi 

As recording in https://github.com/argoproj/argo-workflows/blob/master/CHANGELOG.md. Commit [db58583d2](https://github.com/argoproj/argo-workflows/commit/db58583d297d23bc40364150576ef17a86b2c914) seems change the argoflow behavior. See https://github.com/argoproj/argo-workflows/commit/db58583d297d23bc40364150576ef17a86b2c914.

Maybe dflow need to change the check-step usage.

**Comment by zjgemi** [comment]
fixed.

**Comment by zjgemi** [comment]
https://github.com/deepmodeling/dflow/pull/125
