### ISSUE TITLE
CI test for slurm

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/dflow#94]
# Summary

I have added a CI test for slurm in dpdispatcher (https://github.com/deepmodeling/dpdispatcher/pull/253). So if possible dflow can also add a test for slurm.

**Comment by zjgemi** [comment]
https://github.com/deepmodeling/dflow/pull/106

**Comment by zjgemi** [comment]
The dflow always communicates with slurm cluster via SSH. So I build a docker image (dptechnology/slurm-docker-cluster:latest) including sshd as well as python 3.6. Besides, the image has two manifests for amd64 and arm64 architectures which allows one run slurm docker cluster on Mac with M1 chip.
